# Generated by Django 5.2.4 on 2025-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "telegram_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("token", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Telegram-пользователя",
                "verbose_name_plural": "Telegram-пользователи",
                "db_table": "telegram_user",
            },
        ),
    ]
