# Generated by Django 5.2.4 on 2025-07-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["id"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
