# Generated by Django 5.2.4 on 2025-08-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_products_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ("id",),
                "verbose_name": "Категорию",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
